name: autonomous-drone
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - colored=1.4.2
  - matplotlib=3.3.4
  - numpy=1.20.1
  - opencv=4.5.1
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.8.8
  - pytorch=1.7.0
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - torchvision=0.8.1
  - tqdm=4.59.0
  - pip:
    - astar==0.93
    - keyboard==0.13.5
    - msgpack-rpc-python==0.4.1
    - pyzbar==0.1.8
