name: autonomous-uav
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - colored=1.4.2
  - matplotlib=3.3.2
  - numpy=1.19.2
  - opencv=4.5.1
  - pandas=1.2.1
  - pillow=8.1.0
  - pip=20.3.3
  - pycodestyle=2.6.0
  - python=3.8.5
  - pytorch=1.7.0
  - scikit-learn=0.23.2
  - torchvision=0.8.1
  - tqdm=4.56.0
  - pip:
    - airsim==1.3.0
    - astar==0.93
    - keyboard==0.13.5
