name: autonomous-uav
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - colored=1.4.2
  - matplotlib=3.3.4
  - numpy=1.19.2
  - opencv=4.5.1
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.8.8
  - pytorch=1.7.0
  - scikit-learn=0.24.1
  - torchvision=0.8.1
  - tqdm=4.56.0
  - pip:
    - airsim==1.3.0
    - astar==0.93
    - keyboard==0.13.5
